language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build --stacktrace"

# CI 실행 완료시 메일과 슬랙 알람
notifications:
  email:
    recipients:
      - mjh79017901@gmail.com
  slack:
    rooms:
      - test-8cn7742:GwVyUcsF1m64Ozftimca8VeD#general
      - test-8cn7742:GwVyUcsF1m64Ozftimca8VeD#notificationstest